create schema nhnent_preassign AUTHORIZATION DBA;
set schema nhnent_preassign;

drop table visitorbook if exists;

CREATE TABLE nhnent_preassign.visitorbook
(
    idx INT PRIMARY KEY,
    content VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at TIMESTAMP DEFAULT current_timestamp NOT NULL,
    email VARCHAR(100) NOT NULL,
    passwd CHAR(64) NOT NULL
);

alter table visitorbook alter column idx
set generated by default as identity (start with 1 increment by 1);
